# Generated by Django 4.2 on 2023-08-12 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="book_types",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name="book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("100L", "100Level"),
                            ("200L", "200Level"),
                            ("300L", "300Level"),
                            ("400L", "400Level"),
                            ("500L", "500Level"),
                            ("600L", "600Level"),
                        ],
                        max_length=100,
                    ),
                ),
                ("name_of_book", models.CharField(max_length=300)),
                ("user", models.CharField(max_length=100, verbose_name="auth::user")),
                (
                    "type",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="book.book_types",
                    ),
                ),
            ],
        ),
    ]
