# Generated by Django 4.2 on 2023-08-12 16:36

import django.contrib.auth.context_processors
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0002_remove_book_type_book_book_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="user",
            field=models.CharField(
                max_length=100, verbose_name=django.contrib.auth.context_processors.auth
            ),
        ),
    ]
