# Generated by Django 4.2 on 2023-08-13 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0001_initial"),
        ("book", "0004_alter_book_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="registration.student"
            ),
        ),
    ]
